import { DocumentType, ProcessType } from '@prisma/client';
import { z } from 'zod';

export const portalKeySchema = z.enum(['nepal_passport']);

export type PortalKey = z.infer<typeof portalKeySchema>;

export type PortalFieldType = 'text' | 'date' | 'radio' | 'select';

export const portalSourceDocumentSchema = z.nativeEnum(DocumentType);
export type PortalSourceDocument = z.infer<typeof portalSourceDocumentSchema>;

export interface PortalFieldOption {
  value: string;
  label: string;
  selector?: string;
}

export interface PortalFieldMapping {
  key: string;
  selector: string;
  selectors?: string[];
  source?: string;
  sourceDocumentType?: PortalSourceDocument;
  required?: boolean;
  transform?: 'identity' | 'first_token' | 'rest_tokens';
  fieldType?: PortalFieldType;
  options?: PortalFieldOption[];
  approvalRequired?: boolean;
  formStep?: 'form_1' | 'form_2' | 'form_3' | 'form_4' | 'form_5';
  sectionTitle?: string;
  defaultValue?: string;
}

export interface PortalDefinition {
  key: PortalKey;
  name: string;
  processType: ProcessType;
  urlPatterns: string[];
  fields: PortalFieldMapping[];
  manualSteps?: string[];
  formSelectorPlan?: Array<{
    step: string;
    mode: 'auto' | 'manual' | 'mixed';
    selectors: string[];
    notes?: string;
  }>;
}

export const portalDefinitions: Record<PortalKey, PortalDefinition> = {
  nepal_passport: {
    key: 'nepal_passport',
    name: 'Nepal Passport Portal',
    processType: ProcessType.PASSPORT_APPLICATION,
    urlPatterns: ['https://nepalpassport.gov.np/*', 'https://epassport.immigration.gov.np/*'],
    fields: [
      {
        key: 'passport_type',
        selector: "input[name='radio']",
        selectors: ['#PP', '#PB', '#PS', '#PD', '#PG', '#PT', '#PN'],
        fieldType: 'radio',
        options: [
          { value: 'PP', label: 'Ordinary 34 pages', selector: '#PP' },
          { value: 'PB', label: 'Ordinary 66 pages', selector: '#PB' },
          { value: 'PS', label: 'Service', selector: '#PS' },
          { value: 'PD', label: 'Diplomatic', selector: '#PD' },
          { value: 'PG', label: 'Official', selector: '#PG' },
          { value: 'PT', label: 'Temporary', selector: '#PT' },
          { value: 'PN', label: 'Seamen', selector: '#PN' },
        ],
        defaultValue: 'PP',
        required: true,
        approvalRequired: true,
        formStep: 'form_1',
        sectionTitle: 'Form 1 - Passport Type',
      },
      {
        key: 'appointment_country',
        selector: "mat-select[id='mat-select-0']",
        selectors: ["mat-select[id='mat-select-0']"],
        fieldType: 'select',
        options: [{ value: 'Nepal', label: 'Nepal' }],
        defaultValue: 'Nepal',
        approvalRequired: true,
        formStep: 'form_2',
        sectionTitle: 'Form 2 - Appointment Booking',
      },
      {
        key: 'appointment_province',
        selector: "mat-select[id='mat-select-2']",
        selectors: ["mat-select[id='mat-select-2']"],
        fieldType: 'select',
        options: [
          { value: 'Koshi', label: 'Koshi' },
          { value: 'Madhesh', label: 'Madhesh' },
          { value: 'Bagmati', label: 'Bagmati' },
          { value: 'Gandaki', label: 'Gandaki' },
          { value: 'Lumbini', label: 'Lumbini' },
          { value: 'Karnali', label: 'Karnali' },
          { value: 'Sudurpashchim', label: 'Sudurpashchim' },
        ],
        approvalRequired: true,
        formStep: 'form_2',
        sectionTitle: 'Form 2 - Appointment Booking',
      },
      {
        key: 'appointment_district',
        selector: "mat-select[id='mat-select-3']",
        selectors: ["mat-select[id='mat-select-3']"],
        fieldType: 'select',
        approvalRequired: true,
        formStep: 'form_2',
        sectionTitle: 'Form 2 - Appointment Booking',
      },
      {
        key: 'appointment_location',
        selector: "mat-select[id='mat-select-1']",
        selectors: ["mat-select[id='mat-select-1']"],
        fieldType: 'select',
        approvalRequired: true,
        formStep: 'form_2',
        sectionTitle: 'Form 2 - Appointment Booking',
      },
      {
        key: 'first_name',
        selector: "[formcontrolname='firstName']",
        selectors: ["[formcontrolname='firstName']", "input[name='firstName']"],
        source: 'CITIZENSHIP.fields.name_en',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        required: true,
        transform: 'first_token',
        fieldType: 'text',
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Applicant Details',
      },
      {
        key: 'last_name',
        selector: "[formcontrolname='lastName']",
        selectors: ["[formcontrolname='lastName']", "input[name='lastName']"],
        source: 'CITIZENSHIP.fields.name_en',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        required: true,
        transform: 'rest_tokens',
        fieldType: 'text',
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Applicant Details',
      },
      {
        key: 'gender',
        selector: "input[formcontrolname='gender']",
        selectors: ['#test1', '#test2', '#test3'],
        fieldType: 'radio',
        options: [
          { value: 'M', label: 'Male', selector: '#test1' },
          { value: 'F', label: 'Female', selector: '#test2' },
          { value: 'X', label: 'Other', selector: '#test3' },
        ],
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Applicant Details',
      },
      {
        key: 'citizenship_number',
        selector: "[formcontrolname='citizenNum']",
        selectors: ["[formcontrolname='citizenNum']", "input[name='citizenNum']"],
        source: 'CITIZENSHIP.fields.citizenship_number',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        required: true,
        fieldType: 'text',
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Citizenship Details',
      },
      {
        key: 'date_of_birth',
        selector: "[formcontrolname='dateOfBirth']",
        selectors: ["[formcontrolname='dateOfBirth']", "input[name='dateOfBirth']"],
        source: 'CITIZENSHIP.fields.date_of_birth',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        fieldType: 'date',
        required: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Applicant Details',
      },
      {
        key: 'is_exact_date_of_birth',
        selector: "input[formcontrolname='isExactDateOfBirth']",
        selectors: ['#exact', '#exact2'],
        fieldType: 'radio',
        options: [
          { value: 'true', label: 'Yes', selector: '#exact' },
          { value: 'false', label: 'No', selector: '#exact2' },
        ],
        defaultValue: 'true',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Applicant Details',
      },
      {
        key: 'date_of_birth_bs',
        selector: "[formcontrolname='dateOfBirthBS']",
        selectors: ["[formcontrolname='dateOfBirthBS']", "input[name='dateOfBirthBS']"],
        fieldType: 'date',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Applicant Details',
      },
      {
        key: 'citizenship_issue_district',
        selector: "[formcontrolname='citizenIssuePlaceDistrict']",
        selectors: ["[formcontrolname='citizenIssuePlaceDistrict']", "[name='citizenIssuePlaceDistrict']"],
        source: 'CITIZENSHIP.fields.issue_district',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        fieldType: 'select',
        required: true,
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Citizenship Details',
      },
      {
        key: 'citizenship_issue_date_bs',
        selector: "[formcontrolname='citizenIssueDateBS']",
        selectors: ["[formcontrolname='citizenIssueDateBS']", "input[name='citizenIssueDateBS']"],
        fieldType: 'date',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Citizenship Details',
      },
      {
        key: 'birth_district',
        selector: "mat-select[formcontrolname='birthDistrict']",
        selectors: ["mat-select[formcontrolname='birthDistrict']", "#mat-select-4"],
        source: 'CITIZENSHIP.fields.issue_district',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        fieldType: 'select',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Birth and Nationality',
      },
      {
        key: 'birth_country',
        selector: "mat-select[formcontrolname='birthCountry']",
        selectors: ["mat-select[formcontrolname='birthCountry']", "#mat-select-5"],
        fieldType: 'select',
        options: [{ value: 'Nepal', label: 'Nepal' }],
        defaultValue: 'Nepal',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Birth and Nationality',
      },
      {
        key: 'nationality',
        selector: "mat-select[formcontrolname='nationality']",
        selectors: ["mat-select[formcontrolname='nationality']", "#mat-select-6"],
        fieldType: 'select',
        options: [{ value: 'Nepali', label: 'Nepali' }],
        defaultValue: 'Nepali',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Birth and Nationality',
      },
      {
        key: 'citizenship_issue_place_abroad',
        selector: "mat-select[formcontrolname='citizenIssuePlaceAbroad']",
        selectors: ["mat-select[formcontrolname='citizenIssuePlaceAbroad']", "#mat-select-8"],
        fieldType: 'select',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Citizenship Details',
      },
      {
        key: 'father_first_name',
        selector: "[formcontrolname='fatherFirstName']",
        selectors: ["[formcontrolname='fatherFirstName']", "input[name='fatherFirstName']"],
        source: 'CITIZENSHIP.fields.father_name',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        transform: 'first_token',
        fieldType: 'text',
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Family Details',
      },
      {
        key: 'father_last_name',
        selector: "[formcontrolname='fatherLastName']",
        selectors: ["[formcontrolname='fatherLastName']", "input[name='fatherLastName']"],
        source: 'CITIZENSHIP.fields.father_name',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        transform: 'rest_tokens',
        fieldType: 'text',
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Family Details',
      },
      {
        key: 'mother_first_name',
        selector: "[formcontrolname='motherFirstName']",
        selectors: ["[formcontrolname='motherFirstName']", "input[name='motherFirstName']"],
        source: 'CITIZENSHIP.fields.mother_name',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        transform: 'first_token',
        fieldType: 'text',
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Family Details',
      },
      {
        key: 'mother_last_name',
        selector: "[formcontrolname='motherLastName']",
        selectors: ["[formcontrolname='motherLastName']", "input[name='motherLastName']"],
        source: 'CITIZENSHIP.fields.mother_name',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        transform: 'rest_tokens',
        fieldType: 'text',
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Family Details',
      },
      {
        key: 'nin',
        selector: "[formcontrolname='nin']",
        selectors: ["[formcontrolname='nin']", "input[name='nin']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Citizenship Details',
      },
      {
        key: 'home_phone',
        selector: "[formcontrolname='homePhone']",
        selectors: ["[formcontrolname='homePhone']", "input[name='homePhone']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Details',
      },
      {
        key: 'email',
        selector: "[formcontrolname='email']",
        selectors: ["[formcontrolname='email']", "input[name='email']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Details',
      },
      {
        key: 'main_address_country',
        selector: "mat-select[formcontrolname='mainAddressCountry']",
        selectors: ["mat-select[formcontrolname='mainAddressCountry']", "#mat-select-9"],
        fieldType: 'select',
        options: [{ value: 'Nepal', label: 'Nepal' }],
        defaultValue: 'Nepal',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Main Address',
      },
      {
        key: 'main_address_province',
        selector: "mat-select[formcontrolname='mainAddressProvince']",
        selectors: ["mat-select[formcontrolname='mainAddressProvince']", "#mat-select-10"],
        fieldType: 'select',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Main Address',
      },
      {
        key: 'main_address_district',
        selector: "mat-select[formcontrolname='mainAddressDistrict']",
        selectors: ["mat-select[formcontrolname='mainAddressDistrict']", "#mat-select-11"],
        source: 'CITIZENSHIP.fields.issue_district',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        fieldType: 'select',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Main Address',
      },
      {
        key: 'main_address_municipality',
        selector: "mat-select[formcontrolname='mainAddressMunicipality']",
        selectors: ["mat-select[formcontrolname='mainAddressMunicipality']", "#mat-select-12"],
        fieldType: 'select',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Main Address',
      },
      {
        key: 'main_address_house_number',
        selector: "[formcontrolname='mainAddressHouseNum']",
        selectors: ["[formcontrolname='mainAddressHouseNum']", "input[name='mainAddressHouseNum']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Main Address',
      },
      {
        key: 'main_address_street',
        selector: "[formcontrolname='mainAddressStreetVillage']",
        selectors: ["[formcontrolname='mainAddressStreetVillage']", "input[name='mainAddressStreetVillage']"],
        source: 'CITIZENSHIP.fields.address',
        sourceDocumentType: DocumentType.CITIZENSHIP,
        fieldType: 'text',
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Main Address',
      },
      {
        key: 'main_address_ward',
        selector: "[formcontrolname='mainAddressWard']",
        selectors: ["[formcontrolname='mainAddressWard']", "input[name='mainAddressWard']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Main Address',
      },
      {
        key: 'contact_first_name',
        selector: "[formcontrolname='contactFirstName']",
        selectors: ["[formcontrolname='contactFirstName']", "input[name='contactFirstName']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Address',
      },
      {
        key: 'contact_last_name',
        selector: "[formcontrolname='contactLastName']",
        selectors: ["[formcontrolname='contactLastName']", "input[name='contactLastName']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Address',
      },
      {
        key: 'contact_country',
        selector: "mat-select[formcontrolname='contactCountry']",
        selectors: ["mat-select[formcontrolname='contactCountry']", "#mat-select-13"],
        fieldType: 'select',
        options: [{ value: 'Nepal', label: 'Nepal' }],
        defaultValue: 'Nepal',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Address',
      },
      {
        key: 'contact_province',
        selector: "mat-select[formcontrolname='contactProvince']",
        selectors: ["mat-select[formcontrolname='contactProvince']", "#mat-select-14"],
        fieldType: 'select',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Address',
      },
      {
        key: 'contact_district',
        selector: "mat-select[formcontrolname='contactDistrict']",
        selectors: ["mat-select[formcontrolname='contactDistrict']", "#mat-select-15"],
        fieldType: 'select',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Address',
      },
      {
        key: 'contact_municipality',
        selector: "mat-select[formcontrolname='contactMunicipality']",
        selectors: ["mat-select[formcontrolname='contactMunicipality']", "#mat-select-16"],
        fieldType: 'select',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Address',
      },
      {
        key: 'contact_house_number',
        selector: "[formcontrolname='contactHouseNum']",
        selectors: ["[formcontrolname='contactHouseNum']", "input[name='contactHouseNum']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Address',
      },
      {
        key: 'contact_street',
        selector: "[formcontrolname='contactStreetVillage']",
        selectors: ["[formcontrolname='contactStreetVillage']", "input[name='contactStreetVillage']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Address',
      },
      {
        key: 'contact_ward',
        selector: "[formcontrolname='contactWard']",
        selectors: ["[formcontrolname='contactWard']", "input[name='contactWard']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Address',
      },
      {
        key: 'contact_phone',
        selector: "[formcontrolname='contactPhone']",
        selectors: ["[formcontrolname='contactPhone']", "input[name='contactPhone']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Address',
      },
      {
        key: 'contact_email',
        selector: "[formcontrolname='contactEmail']",
        selectors: ["[formcontrolname='contactEmail']", "input[name='contactEmail']"],
        fieldType: 'text',
        approvalRequired: true,
        formStep: 'form_3',
        sectionTitle: 'Form 3 - Contact Address',
      },
      {
        key: 'applicant_type',
        selector: "input[type='radio'][formcontrolname='isMinor']",
        selectors: [
          "input[type='radio'][formcontrolname='isMinor'][value='false']",
          "input[type='radio'][formcontrolname='isMinor'][value='true']",
        ],
        fieldType: 'radio',
        options: [
          {
            value: 'false',
            label: 'Major',
            selector: "input[type='radio'][formcontrolname='isMinor'][value='false']",
          },
          {
            value: 'true',
            label: 'Minor',
            selector: "input[type='radio'][formcontrolname='isMinor'][value='true']",
          },
        ],
        defaultValue: 'false',
        approvalRequired: true,
        formStep: 'form_4',
        sectionTitle: 'Form 4 - Applicant Category and Uploads',
      },
    ],
    manualSteps: [
      'Step 1: Select passport type radio manually (`#PP` for Ordinary 34 pages is common).',
      'Step 2: Appointment country/province/district/location/timeslot are dynamic and must be selected manually.',
      "Step 4 (guessed): Set major/minor radio manually (likely field around `isMinor` or labels 'Major'/'Minor').",
      "Step 4 (guessed): Upload citizenship front/back images manually via file inputs (likely `input[type='file']`).",
      'Final step: complete captcha manually and click submit.',
    ],
    formSelectorPlan: [
      {
        step: 'Form 1 - Passport type selection',
        mode: 'manual',
        selectors: ['#PP', '#PB', '#PS', '#PD', '#PG', '#PT', '#PN'],
        notes: 'Choose one passport type, then click Proceed.',
      },
      {
        step: 'Form 2 - Appointment booking',
        mode: 'manual',
        selectors: ['#mat-select-0', '#mat-select-1', '#mat-select-2', '#mat-select-3'],
        notes: 'Country/province/district/location/timeslot are dynamic and often require manual selection.',
      },
      {
        step: 'Form 3 - Personal and citizenship details',
        mode: 'auto',
        selectors: [
          "[formcontrolname='firstName']",
          "[formcontrolname='lastName']",
          "[formcontrolname='dateOfBirth']",
          "[formcontrolname='citizenNum']",
          "[formcontrolname='citizenIssuePlaceDistrict']",
          "[formcontrolname='fatherFirstName']",
          "[formcontrolname='fatherLastName']",
          "[formcontrolname='motherFirstName']",
          "[formcontrolname='motherLastName']",
          "[formcontrolname='mainAddressStreetVillage']",
          "[formcontrolname='contactStreetVillage']",
        ],
        notes: 'Autofill targets these fields; date and district may still need manual correction based on input format/options.',
      },
      {
        step: 'Form 4 - Major/minor and uploads (guessed)',
        mode: 'mixed',
        selectors: [
          "input[type='radio'][formcontrolname='isMinor']",
          "input[type='file'][formcontrolname='citizenshipFront']",
          "input[type='file'][formcontrolname='citizenshipBack']",
        ],
        notes: 'Radio often manual; file upload is attempted by extension and may need manual fallback.',
      },
      {
        step: 'Form 5 - Summary and submit',
        mode: 'manual',
        selectors: ["input[name*='captcha']", "[id*='captcha']", "button[type='submit']"],
        notes: 'Captcha and final submit are always manual.',
      },
    ],
  },
};

export function portalKeyFromProcessType(_processType: ProcessType): PortalKey {
  return 'nepal_passport';
}
